### ISSUE TITLE
Incremental training for sparkxgb

### ISSUE THREAD

**Issue by akshayparanjape** [sllynn/spark-xgboost#10]
Is there a way for incremental training/ training with batches for `XGBoostClassifier`?
I am dealing with large size of data and would like to upload chunks of data and train XGBoost in batches. 
I tried the approach as mentioned below:
```

    model1 = xgb.fit(df1)
    parammap1 = model.extractParamMap()
    
    model2a = xgb.fit(df2, parammap1 )
    parammap2 = model.extractParamMap()
    
    model2b = xgb.fit(df2)
```

But I don't see an overall gain of knowledge in the model, i.e
`model2a` has the same performance as `model2b`

Or if my approach is wrong then it would be nice if you could point out the right direction for me
Thanks

**Comment by sllynn** [comment]
I don't know of any way to do this, `extractParamMap` only returns the hyperparameters of the model.

What constraint are you hitting with regards to data size? Available memory in the cluster?

**Comment by akshayparanjape** [comment]
My data size is 800 MB and spark cluster confs are mentioned below:
```
spark driver specs:
core: 1
memory:1G
spark executor specs:
instances:2
core: 2
memory: 2G
```
I get an error for the above data size and config
