### ISSUE TITLE
'JavaPackage' object is not callable while initializing XGBoostClassifier

### ISSUE THREAD

**Issue by akshayparanjape** [sllynn/spark-xgboost#7]
complete error log:
  File "/tmp/spark-303da6d5-399e-4235-ada4-85d8b5a06fb2/train_xgb.py", line 217, in <module>
    train(dfs, input_cols, target_col)
  File "/tmp/spark-303da6d5-399e-4235-ada4-85d8b5a06fb2/train_xgb.py", line 102, in train
    XGBoostClassifier(**xgbParams)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/__init__.py", line 110, in wrapper
  File "/var/data/spark-aa686d96-27e3-4606-93ec-e63bb159082a/spark-b2983255-964a-44f1-8849-a74ac85501a7/userFiles-ad1f6ea8-095c-42df-8cc6-0f668bf8173d/sparkxgb.zip/sparkxgb/xgboost.py", line 85, in __init__
  File "/var/data/spark-aa686d96-27e3-4606-93ec-e63bb159082a/spark-b2983255-964a-44f1-8849-a74ac85501a7/userFiles-ad1f6ea8-095c-42df-8cc6-0f668bf8173d/sparkxgb.zip/sparkxgb/common.py", line 68, in __init__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 69, in _new_java_obj
TypeError: 'JavaPackage' object is not callable

Any sort of help will be highly appreciated

**Comment by sllynn** [comment]
Looks as though you haven't attached the XGBoost4J and XGBoost4J-Spark jars to your cluster.

Follow the instructions here:
https://xgboost.readthedocs.io/en/latest/jvm/index.html#installation-from-maven-repository

**Comment by akshayparanjape** [comment]
I added two jars from here:
 https://repo1.maven.org/maven2/ml/dmlc/xgboost4j/0.72/xgboost4j-0.72.jar
 https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-spark/0.72/xgboost4j-spark-0.72.jar

when I checked the log of my spark-cluster, I can see this:

21/03/26 13:52:37 INFO SparkContext: Added JAR file:/tmp/spark-daca4a15-57d9-4b2c-993a-8103bfbf7fc3/xgboost4j-0.72-javadoc.jar at spark://j-2-1-cc7358786ecec5e8-driver-svc.spark-operator.svc:7078/jars/**xgboost4j-0.72.jar** with timestamp 1616766756761
21/03/26 13:52:37 INFO SparkContext: Added JAR file:/tmp/spark-daca4a15-57d9-4b2c-993a-8103bfbf7fc3/xgboost4j-spark-0.72-javadoc.jar at spark://j-2-1-cc7358786ecec5e8-driver-svc.spark-operator.svc:7078/jars/**xgboost4j-spark-0.72.jar** with timestamp 1616766756761

_this implies that the jars were added_

but I  still get the same error during execution "TypeError: 'JavaPackage' object is not callable" .


the complete error log is here:

`Traceback (most recent call last):
  File "/tmp/spark-820d6fa2-5813-4508-b457-506063d71172/train_xgb.py", line 231, in <module>
    train(dfs, input_cols, target_col)

  File "/tmp/spark-820d6fa2-5813-4508-b457-506063d71172/train_xgb.py", line 100, in train
    XGBoostClassifier(**xgbParams)

  File "/opt/spark/python/lib/pyspark.zip/pyspark/__init__.py", line 110, in wrapper

  File "/var/data/spark-e5795e8d-fafa-49f8-a08c-5679b1689709/spark-33a90afc-20ee-45f6-96fd-7f0c53835518/userFiles-71851d68-edfe-4c44-8faf-bcfb443eef28/sparkxgb.zip/sparkxgb/xgboost.py", line 85, in __init__

  File "/var/data/spark-e5795e8d-fafa-49f8-a08c-5679b1689709/spark-33a90afc-20ee-45f6-96fd-7f0c53835518/userFiles-71851d68-edfe-4c44-8faf-bcfb443eef28/sparkxgb.zip/sparkxgb/common.py", line 68, in __init__

  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 69, in _new_java_obj
TypeError: 'JavaPackage' object is not callable`


Thanks

**Comment by sllynn** [comment]
Can you retry with either version 0.9 or 1.0 of the xgboost4j jars. I haven't tested anything against v0.72.

Also, what version of Spark are you using?

**Comment by akshayparanjape** [comment]
I will try that
I am using spark-3.0.2-bin-hadoop3.2

**Comment by akshayparanjape** [comment]
I tried with version-0.9 but the error persists.

**Comment by akshayparanjape** [comment]
The Error was resolved with the below jars:
https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/1.3.1/xgboost4j_2.12-1.3.1.jar
https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-spark_2.12/1.3.1/xgboost4j-spark_2.12-1.3.1.jar
Thanks @sllynn  for your support :)

**Comment by bestfleer** [comment]
can you tell me where XGBoost4J and XGBoost4J-Spark jars need to be attached? I cannot find these information in https://xgboost.readthedocs.io/en/latest/jvm/index.html#installation-from-maven-repository. Thanks for your help

**Comment by sllynn** [comment]
That rather depends on where you are running Spark. Are you using Databricks? If so, you can attach these JARs directly from Maven using the Cluster UI ([docs](https://docs.databricks.com/libraries/cluster-libraries.html)).

Otherwise, you probably want to set the appropriate spark confs  when creating the SparkSession: `spark.jars.packages` if you're supplying Maven coords or `spark.jars` if you have the files downloaded. More info [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.SparkSession.builder.config.html#pyspark.sql.SparkSession.builder.config) and [here](https://spark.apache.org/docs/latest/configuration.html) and a practical example [here](https://github.com/databrickslabs/mosaic/blob/33c83596e24f1334028da33582cca26090e8c347/python/test/utils/spark_test_case.py#L18).

**Comment by bohemia420** [comment]
I tried putting it in `spark.jars` as well as `addPyFiles`, like below:
```
spark.sparkContext.addPyFile('/home/sumit/Downloads/xgboost4j_2.12-1.3.1.jar')
spark.sparkContext.addPyFile('/home/sumit/Downloads/xgboost4j-spark_2.12-1.3.1.jar')

spark.sparkContext.setSystemProperty('spark.jars','/home/sumit/Downloads/xgboost4j_2.12-1.3.1.jar')
spark.sparkContext.setSystemProperty('spark.jars','/home/sumit/Downloads/xgboost4j-spark_2.12-1.3.1.jar')
```

and I am using `PySpark==3.3.1`, and just launching normally the `jupyter notebook`

```
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('SHAP').master("local[16]").getOrCreate()
spark.sparkContext.setSystemProperty('spark.executor.memory', '32g')
spark.sparkContext.setSystemProperty('spark.executor.cores', '16')
```

however I still keep getting the JavaPackage object is not callable error:
```
/usr/local/lib/python3.10/dist-packages/spark_xgboost-0.90-py3.10.egg/sparkxgb/xgboost.py in __init__(self, alpha, baseMarginCol, baseScore, cacheTrainingSet, checkpointInterval, checkpointPath, colsampleBylevel, colsampleBytree, contribPredictionCol, eta, evalMetric, featuresCol, gamma, growPolicy, interactionConstraints, labelCol, lambda_, lambdaBias, leafPredictionCol, maxBins, maxDeltaStep, maxDepth, maxLeaves, maximizeEvaluationMetrics, minChildWeight, missing, monotoneConstraints, normalizeType, nthread, numClass, numEarlyStoppingRounds, numRound, numWorkers, objective, objectiveType, predictionCol, probabilityCol, rateDrop, rawPredictionCol, sampleType, scalePosWeight, seed, silent, sketchEps, skipDrop, subsample, thresholds, timeoutRequestWorkers, trainTestRatio, treeLimit, treeMethod, useExternalMemory, verbosity, weightCol)
     83                  verbosity=1,
     84                  weightCol=None):
---> 85         super(XGBoostClassifier, self).__init__(classname="ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier")
     86         kwargs = self._input_kwargs
     87         if "lambda_" in kwargs:

/usr/local/lib/python3.10/dist-packages/spark_xgboost-0.90-py3.10.egg/sparkxgb/common.py in __init__(self, classname)
     66         super(XGboostEstimator, self).__init__()
     67         self.__class__._java_class_name = classname
---> 68         self._java_obj = self._new_java_obj(classname, self.uid)
     69         self._create_params_from_java()
     70         self._create_param_getters_and_setters()

~/.local/lib/python3.10/site-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     84             java_obj = getattr(java_obj, name)
     85         java_args = [_py2java(sc, arg) for arg in args]
---> 86         return java_obj(*java_args)
     87 
     88     @staticmethod

TypeError: 'JavaPackage' object is not callable.
```

Where am I erring?
spark-3.0.0-bin-hadoop2.7$ ./bin/pyspark --jars /home/sumit/Downloads/xgboost4j-spark_2.12-1.3.1.jar,/home/sumit/Downloads/xgboost4j_2.12-1.3.1.jar
edit: I think over through the Jupyter notebook, it didnt work, but launching a `./bin/pyspark` shell and running line-by-line got me past the issue. Yes, I only had to pass 
```
spark-3.0.0-bin-hadoop2.7$ ./bin/pyspark --jars /home/sumit/Downloads/xgboost4j-spark_2.12-1.3.1.jar,/home/sumit/Downloads/xgboost4j_2.12-1.3.1.jar
```

however now, as per the example, the following error shows up for `model = cv.fit(train_sdf_prepared)`
```
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 22 more
```

**Comment by bohemia420** [comment]
@akshayparanjape  @sllynn  I tried running the very NB: https://github.com/sllynn/spark-xgboost/blob/master/examples/spark-xgboost_adultdataset.ipynb 

on Spark 3.0.2 with the JARs you suggested above : 
https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/1.3.1/xgboost4j_2.12-1.3.1.jar
https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-spark_2.12/1.3.1/xgboost4j-spark_2.12-1.3.1.jar

yet I get the errors:
```
java.io.IOException: Cannot run program "python": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:416)
	at java.base/java.lang.Runtime.exec(Runtime.java:313)
	at ml.dmlc.xgboost4j.java.RabitTracker.startTrackerProcess(RabitTracker.java:136)
	at ml.dmlc.xgboost4j.java.RabitTracker.start(RabitTracker.java:170)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:436)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:593)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:199)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 22 more
```

I am running so as:
`./bin/spark-submit --master local[*] --jars /home/sumit/Downloads/xgboost4j-spark_2.12-1.3.1.jar,/home/sumit/Downloads/xgboost4j_2.12-1.3.1.jar hello.py` 

where hello.py is the following excerpt of the NB:
```
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('SHAP').master("local[*]").getOrCreate()
spark.sparkContext.setSystemProperty('spark.executor.memory', '32g')
spark.sparkContext.setSystemProperty('spark.executor.cores', '16')
spark.sparkContext.setSystemProperty('spark.jars.packages', 'databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11')
#spark.sparkContext.setSystemProperty('spark.jars','/home/sumit/Downloads/xgboost4j_2.12-1.4.1.jar')
#spark.sparkContext.setSystemProperty('spark.jars','/home/sumit/Downloads/xgboost4j-spark_2.12-1.4.1.jar')

#spark.sparkContext.addPyFile('/home/sumit/Downloads/xgboost4j_2.12-1.4.1.jar')
#spark.sparkContext.addPyFile('/home/sumit/Downloads/xgboost4j-spark_2.12-1.4.1.jar')

from sparkxgb import XGBoostClassifier, XGBoostRegressor

from pyspark.sql.types import StringType

from pyspark.ml import Pipeline
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml.evaluation import MulticlassClassificationEvaluator, BinaryClassificationEvaluator
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator

col_names = [
  "age", "workclass", "fnlwgt",
  "education", "education-num",
  "marital-status", "occupation",
  "relationship", "race", "sex",
  "capital-gain", "capital-loss",
  "hours-per-week", "native-country",
  "label"
]

train_sdf, test_sdf = (
  spark.read.csv(
    path="/home/sumit/Downloads/adult.data",
    inferSchema=True  
  )
  .toDF(*col_names)
  .repartition(200)
  .randomSplit([0.8, 0.2])
)

string_columns = [fld.name for fld in train_sdf.schema.fields if isinstance(fld.dataType, StringType)]
string_col_replacements = [fld + "_ix" for fld in string_columns]
string_column_map=list(zip(string_columns, string_col_replacements))
target = string_col_replacements[-1]
predictors = [fld.name for fld in train_sdf.schema.fields if not isinstance(fld.dataType, StringType)] + string_col_replacements[:-1]

si = [StringIndexer(inputCol=fld[0], outputCol=fld[1]) for fld in string_column_map]
va = VectorAssembler(inputCols=predictors, outputCol="features")
pipeline = Pipeline(stages=[*si, va])
fitted_pipeline = pipeline.fit(train_sdf.union(test_sdf))
     
train_sdf_prepared = fitted_pipeline.transform(train_sdf)

xgbParams = dict(
  eta=0.1,
  maxDepth=2,
  missing=0.0,
  objective="binary:logistic",
  numRound=5,
  numWorkers=2
)

xgb = (
  XGBoostClassifier(**xgbParams)
  .setFeaturesCol("features")
  .setLabelCol("label_ix")
)

bce = BinaryClassificationEvaluator(
  rawPredictionCol="rawPrediction",
  labelCol="label_ix"
)

param_grid = (
  ParamGridBuilder()
  .addGrid(xgb.eta, [1e-1, 1e-2, 1e-3])
  .addGrid(xgb.maxDepth, [2, 4, 8])
  .build()
)

cv = CrossValidator(
  estimator=xgb,
  estimatorParamMaps=param_grid,
  evaluator=bce,#mce,
  numFolds=5
)

model = cv.fit(train_sdf_prepared)
```

**Comment by bohemia420** [comment]
> @akshayparanjape @sllynn I tried running the very NB: https://github.com/sllynn/spark-xgboost/blob/master/examples/spark-xgboost_adultdataset.ipynb
> 
> on Spark 3.0.2 with the JARs you suggested above : https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/1.3.1/xgboost4j_2.12-1.3.1.jar https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-spark_2.12/1.3.1/xgboost4j-spark_2.12-1.3.1.jar
> 
> yet I get the errors:
> 
> ```
> java.io.IOException: Cannot run program "python": error=2, No such file or directory
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:592)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:416)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:313)
> 	at ml.dmlc.xgboost4j.java.RabitTracker.startTrackerProcess(RabitTracker.java:136)
> 	at ml.dmlc.xgboost4j.java.RabitTracker.start(RabitTracker.java:170)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:436)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:593)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:199)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
> 	at org.apache.spark.ml.Predictor.fit(Predictor.scala:150)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.io.IOException: error=2, No such file or directory
> 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> 	... 22 more
> ```
> 
> I am running so as: `./bin/spark-submit --master local[*] --jars /home/sumit/Downloads/xgboost4j-spark_2.12-1.3.1.jar,/home/sumit/Downloads/xgboost4j_2.12-1.3.1.jar hello.py`
> 
> where hello.py is the following excerpt of the NB:
> 
> ```
> from pyspark.sql import SparkSession
> 
> spark = SparkSession.builder.appName('SHAP').master("local[*]").getOrCreate()
> spark.sparkContext.setSystemProperty('spark.executor.memory', '32g')
> spark.sparkContext.setSystemProperty('spark.executor.cores', '16')
> spark.sparkContext.setSystemProperty('spark.jars.packages', 'databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11')
> #spark.sparkContext.setSystemProperty('spark.jars','/home/sumit/Downloads/xgboost4j_2.12-1.4.1.jar')
> #spark.sparkContext.setSystemProperty('spark.jars','/home/sumit/Downloads/xgboost4j-spark_2.12-1.4.1.jar')
> 
> #spark.sparkContext.addPyFile('/home/sumit/Downloads/xgboost4j_2.12-1.4.1.jar')
> #spark.sparkContext.addPyFile('/home/sumit/Downloads/xgboost4j-spark_2.12-1.4.1.jar')
> 
> from sparkxgb import XGBoostClassifier, XGBoostRegressor
> 
> from pyspark.sql.types import StringType
> 
> from pyspark.ml import Pipeline
> from pyspark.ml.feature import StringIndexer, VectorAssembler
> from pyspark.ml.evaluation import MulticlassClassificationEvaluator, BinaryClassificationEvaluator
> from pyspark.ml.tuning import ParamGridBuilder, CrossValidator
> 
> col_names = [
>   "age", "workclass", "fnlwgt",
>   "education", "education-num",
>   "marital-status", "occupation",
>   "relationship", "race", "sex",
>   "capital-gain", "capital-loss",
>   "hours-per-week", "native-country",
>   "label"
> ]
> 
> train_sdf, test_sdf = (
>   spark.read.csv(
>     path="/home/sumit/Downloads/adult.data",
>     inferSchema=True  
>   )
>   .toDF(*col_names)
>   .repartition(200)
>   .randomSplit([0.8, 0.2])
> )
> 
> string_columns = [fld.name for fld in train_sdf.schema.fields if isinstance(fld.dataType, StringType)]
> string_col_replacements = [fld + "_ix" for fld in string_columns]
> string_column_map=list(zip(string_columns, string_col_replacements))
> target = string_col_replacements[-1]
> predictors = [fld.name for fld in train_sdf.schema.fields if not isinstance(fld.dataType, StringType)] + string_col_replacements[:-1]
> 
> si = [StringIndexer(inputCol=fld[0], outputCol=fld[1]) for fld in string_column_map]
> va = VectorAssembler(inputCols=predictors, outputCol="features")
> pipeline = Pipeline(stages=[*si, va])
> fitted_pipeline = pipeline.fit(train_sdf.union(test_sdf))
>      
> train_sdf_prepared = fitted_pipeline.transform(train_sdf)
> 
> xgbParams = dict(
>   eta=0.1,
>   maxDepth=2,
>   missing=0.0,
>   objective="binary:logistic",
>   numRound=5,
>   numWorkers=2
> )
> 
> xgb = (
>   XGBoostClassifier(**xgbParams)
>   .setFeaturesCol("features")
>   .setLabelCol("label_ix")
> )
> 
> bce = BinaryClassificationEvaluator(
>   rawPredictionCol="rawPrediction",
>   labelCol="label_ix"
> )
> 
> param_grid = (
>   ParamGridBuilder()
>   .addGrid(xgb.eta, [1e-1, 1e-2, 1e-3])
>   .addGrid(xgb.maxDepth, [2, 4, 8])
>   .build()
> )
> 
> cv = CrossValidator(
>   estimator=xgb,
>   estimatorParamMaps=param_grid,
>   evaluator=bce,#mce,
>   numFolds=5
> )
> 
> model = cv.fit(train_sdf_prepared)
> ```

resolved, my problem was the xgboost4j-spark being unable to find "python"- no alias/env var worked. but a symlink to point to python3(preferably 3.7).
